apiVersion: v1
kind: Service
metadata:
  name: hwapp-service
  labels:
    app: hwapp-label
spec:
  selector:
    app: hwapp-label
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31200