output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "cluster_security_group_worker_group_mgmt_one_id" {
  description = "Security group ids for attached to the cluster worker nodes"
  value       = aws_security_group.worker_group_mgmt_one
}

output "cluster_security_group_additional_all_worker_mgmt_id" {
  description = "Additional Security group ids for attached to the cluster worker nodes"
  value       = aws_security_group.all_worker_mgmt
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}
